import Head from 'next/head';
import { ThemeButton } from '../ThemeButton';
import { ContentContainerNonApp } from './styles';
type MainProps = {
  children: JSX.Element;
};

export default function NonAppLayout({ children }: MainProps) {
  return (
    <div>
      <Head>
        <title>Limelight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentContainerNonApp>
        <ThemeButton />
        {children}
      </ContentContainerNonApp>
    </div>
  );
}
